data:
  extract: false
  root: ${oc.env:HOME}/thesis/spoof/data/casia
  train_videos: ${.root}/train/data/train
  train_metadata: ${.root}/train/meta/train
  train_images: ${.root}/images/train
  train_annotations: ${.root}/images/train/annotations.json
  test_videos: ${.root}/test/data/test
  test_metadata: ${.root}/test/meta/test
  test_images: ${.root}/images/test
  test_annotations: ${.root}/images/test/annotations.json
  ext: .avi
  meta: .json
  batch_size: 512
  face_region:
    size: 224
model:
  in_channels: 3
  num_classes: 2
train:
  epochs: 10
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

criterion:
  _target_: torch.nn.BCELoss

device: cuda
