model:
  name: vit_large_patch16_224
  save_path: ${oc.env:HOME}/mipt/thesis/code/spoof/models/model.ckpt
  params:
    img_size : 224
    in_chans : 3
    num_classes : 2
    global_pool : 'token'
data:
  root: ${oc.env:HOME}/mipt/thesis/code/spoof/data/casia
  train: ${.root}/train
  test: ${.root}/test
  batch_size: 512


dataset:
  root: ${oc.env:HOME}/mipt/thesis/code/spoof/data/casia
  params:
    annotations_path: ${..root}/train_annotations.csv
    video_root: ${..root}/train/data/train
    img_root: ${..root}/images/train
    extract: false

train:
  epochs: 10
  batch_size: 25
  lr: 1e-3
  num_workers: 10

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

criterion:
  _target_: torch.nn.BCELoss

device: mps
