data:
  extract: false
  root: ${oc.env:HOME}/mipt/thesis/code/spoof/data/casia
  train_videos: ${.root}/train/data/train
  train_metadata: ${.root}/train/meta/train
  train_images: ${.root}/images/train
  train_annotations: ${.root}/images/train/annotations.json
  ext: .avi
  meta: .json
  batch_size: 200
  face_region:
    size: 224
model:
  in_channels: 3
  num_classes: 2
train:
  epochs: 10
