dataset:
  name: casia
  train_src: ${oc.env:HOME}/mipt/thesis/datasets/casia/train/data/train
  test_src: ${oc.env:HOME}/mipt/thesis/datasets/casia/test/data/test
  train_dest: ${oc.env:HOME}/tmp/train
  test_dest: ${oc.env:HOME}/tmp/test
  ext: .avi
  meta: .json
