model:
  name: vit_large_patch16_224
  params:
    img_size : 224
    in_chans : 3
    num_classes : 2
    global_pool : 'token'

dataset:
  root: ${oc.env:HOME}/mipt/thesis/code/spoof/data/casia
  params:
    annotations_path: ${..root}/train_annotations.json
    video_root: ${..root}/train/data/train
    img_root: ${..root}/images/train
    extract: false

train:
  epochs: 10
  batch_size: 25
  num_workers: 4

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

criterion:
  _target_: torch.nn.BCELoss

device: mps
