data:
  train: ${oc.env:HOME}/mipt/thesis/datasets/casia/train/data/train
  train_frames: ${oc.env:HOME}/mipt/thesis/code/spoof/data/train_frames
  test: ${oc.env:HOME}/mipt/thesis/datasets/casia/test/data/test
  test_frames: ${oc.env:HOME}/mipt/thesis/code/spoof/data/test_frames
  annotations: ${oc.env:HOME}/mipt/thesis/code/spoof/data/train.txt
  train_meta: ${oc.env:HOME}/mipt/thesis/code/spoof/data/train_meta.txt
  ext: .avi
  meta: .json
model:
  in_channels: 3
  num_classes: 2
train:
  epochs: 10
