data:
  extract: false
  root: ${oc.env:HOME}/mipt/thesis/code/spoof/data/casia
  train_videos: ${.root}/train/data
  annotations: ${.root}/annotations.txt
  train_meta: ${.root}/meta.txt
  train_frames: ${.root}/train_frames
  test: ${.root}/test/data/casia/test
  test_frames: ${.root}/test_frames
  ext: .avi
  meta: .json
  batch_size: 200
  face_region:
    size: 224
model:
  in_channels: 3
  num_classes: 2
train:
  epochs: 10
